name: simple_deployment_pipeline

on:
  push:
    branches:
      - main
  pull_request: 

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build
        run: npm run build

  deploy:
    needs: build_and_test
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        run: echo "Deploying app..."
