name: Health Check

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  health_check:
    runs-on: ubuntu-latest

    steps:
      - name: Check website health
        uses: jtalk/url-health-check-action@v3
        with:
          url: .github/workflows/healthcheck.yml
          max-attempts: 3
          retry-delay: 5s